development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: spree-scrape_development
  pool:     5
  username: postgres
  password: postgres
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: spree-scrape_test
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  host:     <%= ENV['HOST'] %>
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  pool:     5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  template: template0
  # url:      postgres://sxkvorxfdfybnp:mtQSiQn81yhtHlV2jnkivQpnR6@ec2-54-243-203-141.compute-1.amazonaws.com:5432/dclfn81mhovlv3
